{
 "title": "Bill Collection SMS Application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Application",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=\"sms-application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"sms-application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"sms-application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"sms-application\"}",
     "legendFormat": "Total CPU Usage"
    },
    {
     "expr": "process_cpu_usage{job=\"sms-application\"}",
     "legendFormat": "App CPU Usage"
    }
   ]
  },
  {
   "title": "Logger",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"debug\"}",
     "legendFormat": "Debug"
    },
    {
     "expr": "logback_events_total{level=\"error\"}",
     "legendFormat": "Error"
    },
    {
     "expr": "logback_events_total{level=\"trace\"}",
     "legendFormat": "Trace"
    },
    {
     "expr": "logback_events_total{level=\"warn\"}",
     "legendFormat": "Warn"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tasks_scheduled_execution_seconds_sum {code_function=\"triggerBanglalink\",code_namespace=\"com.desco.sms.controller.SmsController\" } [30m])",
     "legendFormat": "BL"
    },
    {
     "expr": "rate(tasks_scheduled_execution_seconds_sum {code_function=\"triggerGp\",code_namespace=\"com.desco.sms.controller.SmsController\" } [30m])",
     "legendFormat": "GP"
    },
    {
     "expr": "rate(tasks_scheduled_execution_seconds_sum {code_function=\"triggerRobi\",code_namespace=\"com.desco.sms.controller.SmsController\" } [30m])",
     "legendFormat": "Robi"
    },
    {
     "expr": "rate(tasks_scheduled_execution_seconds_sum {code_function=\"triggerTeletalk\",code_namespace=\"com.desco.sms.controller.SmsController\" } [30m])",
     "legendFormat": "Teletalk"
    }
   ]
  },
  {
   "title": "Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_sum{exception=\"None\",method=\"pendingSmsCount\",repository=\"SmsRepository\",state=\"SUCCESS\"} [30m])",
     "legendFormat": "Pending Count"
    },
    {
     "expr": "rate(spring_data_repository_invocations_seconds_sum{exception=\"None\",method=\"findUnsentSms\",repository=\"SmsRepository\",state=\"SUCCESS\"} [30m])",
     "legendFormat": "Unsent SMS"
    },
    {
     "expr": "rate(spring_data_repository_invocations_seconds_sum{exception=\"None\",method=\"findSentSms\",repository=\"SmsRepository\",state=\"SUCCESS\"} [30m])",
     "legendFormat": "Sent SMS"
    },
    {
     "expr": "rate(spring_data_repository_invocations_seconds_sum{exception=\"None\",method=\"pendingDlrCount\",repository=\"SmsRepository\",state=\"SUCCESS\"} [30m])",
     "legendFormat": "DLR Count"
    }
   ]
  }
 ]
}