{
 "title": "DESCO Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Division",
    "label": "S & D",
    "query": "SELECT  sdd.DIVISION_NAME FROM SALES_DISTRIBUTION_DIVISION sdd; "
   }
  ]
 },
 "panels": [
  { "title": "Row 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "                    Consumer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.consumer FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "Consumer Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT IFNULL(SUM(mpd.consumer_nos),0) AS Prepaid, (pm.consumer -SUM(mpd.consumer_nos)) Postpaid\r\nFROM `MOD_PREPAID_DATA` mpd, PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and mpd.DIVISION_ID = snd.division_id AND mpd.`YEAR` = (SELECT MAX(`YEAR`) from MOD_PREPAID_DATA) \r\nAND mpd.`MONTH` = (SELECT MAX(`MONTH`) from MOD_PREPAID_DATA WHERE `YEAR`= (SELECT MAX(`YEAR`) from MOD_PREPAID_DATA)) \r\nAND pm.`year` = mpd.`YEAR` AND mpd.DIVISION_ID = pm.division_id AND pm.`month` = mpd.`MONTH` \r\ngroup by mpd.year, mpd.`MONTH`, snd.division_id ;"
    }
   ]
  },
  {
   "title": "Consumer Pattern",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT \"Residential\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('A', 'MT1') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"Commercial\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('E', 'MT2','HT2') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"Industrial\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('C1', 'MT3','HT3') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"Other\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff not IN ('A', 'MT1','E', 'MT2','HT2','C1', 'MT3','HT3') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\""
    }
   ]
  },
  {
   "title": "Connection Pattern",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT \"0.23/0.4 KV\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('A', 'B', 'C1', 'C2', 'D1', 'D2', 'D3','E','T') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"11 KV\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff LIKE 'MT%' AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"33 KV\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff LIKE 'HT%' AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"132/230 KV\" as type, sum(ptf.consumer_nos) as consumer \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff LIKE 'EHT%' AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\""
    }
   ]
  },
  { "title": "Row 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Energy Import",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_import_unit FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "Energy Sold",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_sales_unit FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "System Loss",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_system_loss FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "Peak Load",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "WITH LatestFiscalYear AS (SELECT DISTINCT `YEAR` AS fiscal_year_start FROM `MAXIMUM_LOAD_DEMAND` WHERE `MONTH` > 6 ORDER BY `YEAR` DESC LIMIT 1),\r\nLatestFiscalYearEnd AS (SELECT fiscal_year_start + 1 AS fiscal_year_end FROM LatestFiscalYear)\r\nSELECT MAX(`MAX_LOAD`) AS MaxLoad\r\nFROM desco.`MAXIMUM_LOAD_DEMAND` mld, desco.SALES_DISTRIBUTION_DIVISION snd  \r\nWHERE snd.DIVISION_NAME=\"$Division\" AND mld.DIVISION_ID = snd.DIVISION_ID\r\nAND (\r\n    (`YEAR` = (SELECT fiscal_year_start FROM LatestFiscalYear) AND `MONTH` > 6) \r\n    OR \r\n    (`YEAR` = (SELECT fiscal_year_end FROM LatestFiscalYearEnd) AND `MONTH` < 7)\r\n);"
    }
   ]
  },
  {
   "title": "Consumption Pattern",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT \"Residential\" as type, sum(ptf.ytd_unit) as consumption \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('A', 'MT1') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"Commercial\" as type, sum(ptf.ytd_unit) as consumption \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('E', 'MT2','HT2') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"Industrial\" as type, sum(ptf.ytd_unit) as consumption \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff IN ('C1', 'MT3','HT3') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\"\r\nUNION \r\nSELECT \"Other\" as type, sum(ptf.ytd_unit) as consumption \r\nFROM `PUBLISHED_TRF_WISE_MOD`ptf, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE ptf.division_id = snd.DIVISION_ID AND ptf.tariff not IN ('A', 'MT1','E', 'MT2','HT2','C1', 'MT3','HT3') AND ptf.year =(SELECT MAX(`YEAR`) from desco.PUBLISHED_TRF_WISE_MOD) \r\nAND ptf.month= (SELECT MAX(`MONTH`) from PUBLISHED_TRF_WISE_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_TRF_WISE_MOD)) \r\nand snd.DIVISION_NAME = \"$Division\""
    }
   ]
  },
  { "title": "Row 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Bill Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currency:৳" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_bill_amount FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "Collection Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currency:৳" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_coll_amount FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "Collection to Bill Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_bc_ratio\r\nFROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  {
   "title": "Collection to Import Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT pm.ytd_ci_ratio \r\nFROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd\r\nWHERE snd.division_name=\"$Division\" and pm.DIVISION_ID = snd.division_id AND pm.`YEAR` = (SELECT MAX(`YEAR`) from PUBLISHED_MOD) \r\nAND pm.`MONTH` = (SELECT MAX(`MONTH`) from PUBLISHED_MOD WHERE `YEAR`= (SELECT MAX(`YEAR`) from PUBLISHED_MOD ));"
    }
   ]
  },
  { "title": "Row 111", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Peak Demand",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT concat(year,\"-\", month) \"year-month\",  MAX_LOAD \"Maximum Demand\" FROM (\r\nSELECT year, month, mld.MAX_LOAD FROM MAXIMUM_LOAD_DEMAND mld, SALES_DISTRIBUTION_DIVISION snd\r\nWHERE mld.DIVISION_ID = snd.division_id AND snd.DIVISION_NAME =\"$Division\"\r\nORDER BY year DESC, month DESC LIMIT 18 ) as sub\r\nORDER BY year ASC, month ASC;"
    }
   ]
  },
  {
   "title": "Account Receivables Equivalent Month",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT CONCAT(year,\"-\",`month`) \"year-month\",  acc_receivable_eqv_month \"A/C Receivables Equivalent Month\" from(\r\nSELECT year, month, pm.acc_receivable_eqv_month \r\nfrom desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd WHERE snd.DIVISION_ID = pm.division_id \r\nAND snd.DIVISION_NAME =\"$Division\"\r\nORDER BY `year` DESC, month desc LIMIT 18) as data order by year,month;"
    }
   ]
  },
  {
   "title": "System Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "desco",
     "rawSql": "SELECT STR_TO_DATE(CONCAT(year,'-',LPAD(month,2,'0'),'-01'),'%Y-%m-%d') AS time, system_loss AS value\r\nFROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd WHERE snd.division_name = \"$Division\" and snd.division_id = pm.division_id;"
    },
    {
     "dataset": "desco",
     "rawSql": "SELECT\r\n  STR_TO_DATE(\r\n    CONCAT(year, '-', LPAD(month, 2, '0'), '-01'),\r\n    '%Y-%m-%d'\r\n  ) AS time, ytd_system_loss AS value FROM desco.PUBLISHED_MOD pm, desco.SALES_DISTRIBUTION_DIVISION snd \r\n  WHERE snd.division_name = \"$Division\" and snd.division_id = pm.division_id;"
    }
   ]
  }
 ]
}